name: Commit CI

on:
  push:
    branches: [master]

jobs:
  build-winform:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore "./src/IME WL Converter Win"

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish "./src/IME WL Converter Win"

      - name: Archive Release
        run: 7z a -tzip imewlconverter_Windows.zip publish/

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "imewlconverter_Windows.zip"
          allowUpdates: true
          prerelease: true
          commit: master
          tag: "preview"
          name: "Preview"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-cmd:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./src/ImeWlConverterCmd

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish ./src/ImeWlConverterCmd

      - name: Archive Release
        run: tar -czf imewlconverter_${{ runner.os }}.tar.gz publish/*

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "imewlconverter_${{ runner.os }}.tar.gz"
          allowUpdates: true
          prerelease: true
          commit: master
          tag: "preview"
          name: "Preview"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-mac-arm64:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./src/ImeWlConverterCmd

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish ./src/ImeWlConverterCmd -a arm64

      - name: Archive Release
        run: tar -czf imewlconverter_${{ runner.os }}-aarch64.tar.gz publish/*

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "imewlconverter_${{ runner.os }}-aarch64.tar.gz"
          allowUpdates: true
          prerelease: true
          commit: master
          tag: "preview"
          name: "Preview"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
