name: Pull Request CI

on:
  pull_request:
    branches: [master]

jobs:
  build-winform:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore "./src/IME WL Converter Win"

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish "./src/IME WL Converter Win"

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WinFormApp
          path: ./publish

  build-cmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./src/ImeWlConverterCmd
      # - name: Build
      #   run: dotnet build --no-restore ./src/ImeWlConverterCmd

      - name: Test
        run: dotnet test --no-build --verbosity normal ./src/ImeWlConverterCoreTest/ImeWlConverterCoreTest.csproj

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish ./src/ImeWlConverterCmd

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Cmd
          path: ./publish
